server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/musicdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Geliştirme aşamasında "update", üretimde "validate" önerilir
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG


